# Each new term in the Fibonaccisequence is generated by adding the previous 
# two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89
# write a program to generate nth term of fibbonacci series using recursion.

def fib(n):
    if n == 1 or n == 0 :
        return 1
    else:
        return fib(n-1) + fib(n-2)
    
